tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Cross-platform make
brew "cmake"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Plugin manager for the Fish shell
brew "fisher"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Simple terminal UI for git commands
brew "lazygit"
# Mac App Store command-line interface
brew "mas"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim", args: ["HEAD"]
# Platform built on V8 to build network applications
brew "node"
# Development kit for the Java programming language
brew "openjdk"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Safe, concurrent, practical language
brew "rust"
# Cross-shell prompt for astronauts
brew "starship"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Terminal multiplexer
brew "tmux"
# Command-line interface for Vercel
brew "vercel-cli"
# Generator for LS_COLORS with support for multiple color themes
brew "vivid"
# Internet file retriever
brew "wget"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# E-books management software
cask "calibre"
# API documentation browser and code snippet manager
cask "dash"
# Offline toolbox for developers
cask "devutils"
# Voice and text chat software
cask "discord"
# Downloads videos from different websites
cask "downie"
# Download manager with a torrent client
cask "folx"
# Typeface made for developers
cask "font-jetbrains-mono"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2-beta"
# Spot and merge differences in text and image files or folders
cask "kaleidoscope"
# Media player
cask "movist-pro"
# HTTP client that helps testing and describing APIs
cask "paw"
# Converts and edits video, audio or image files
cask "permute"
# Peer to peer Bitorrent client
cask "qbittorrent"
# Control your tools with a few keystrokes
cask "raycast"
# Team communication and collaboration software
cask "slack"
# Sound and audio controller
cask "soundsource"
# Messaging app with a focus on speed and security
cask "telegram"
# File transfer application
cask "transmit"
# Open-source code editor
cask "visual-studio-code"
# Video communication and virtual meeting platform
cask "webex"
# Video communication and virtual meeting platform
cask "zoom"
mas "Craft", id: 1487937127
mas "Endel", id: 1484348796
mas "Infuse", id: 1136220934
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Mela", id: 1568924476
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Peek", id: 1554235898
mas "Pixelmator Pro", id: 1289583905
mas "Reeder", id: 1529448980
mas "Tampermonkey", id: 1482490089
mas "WeChat", id: 836500024
mas "Xcode", id: 497799835
