require('plugins')
require('autocmd')
require('globals')
require('keymaps')
require('colorscheme')
-- require('plugins.vimspector')
require('plugins.dap')
require('plugins.treesitter')
require('plugins.indent-blankline')
require('plugins.gitsigns')
require('plugins.lualine')
require('plugins.mason')
require('plugins.nvim-tree')
require('plugins.colorizer')
require('plugins.telescope')
-- require('plugins.stabilize')
require('plugins.session-manager')
-- require('plugins.auto-session')
require("plugins.project")
require('plugins.tmux')
require('plugins.cmp')
require('plugins.lsp')
require('plugins.autopairs')
require('sqlite')
-- require('plugins.alpha')
require('plugins.notify')
