-- require('user.vimspector')
require('user.dap')
require('user.treesitter')
require('user.indent-blankline')
require('user.gitsigns')
require('user.lualine')
require('user.mason')
require('user.nvim-tree')
require('user.colorizer')
require('user.telescope')
-- require('user.stabilize')
require('user.session-manager')
-- require('user.auto-session')
require("user.project")
require('user.tmux')
require('user.cmp')
require('user.lsp')
require('user.autopairs')
require('sqlite')
-- require('user.alpha')
require('user.notify')
